name = "helix"
version = "1.0.0"
target = "javascript"
description = "Immutable ESTA DNA"
gleam = ">= 1.11.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.6.0"
